spring:
  application:
    name: BetterTapeBot
  datasource:
    url: jdbc:postgresql://localhost:5432/bettertapebot
    username: changeme_app_user
    password: changeme_app_password
  liquibase:
    url: jdbc:postgresql://localhost:5432/bettertapebot
    user: changeme_migration_user
    password: changeme_migration_password
  jpa:
    hibernate:
      ddl-auto: validate
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
better-tape-bot:
  gdpr:
    resource: file:/config/dsgvo.txt
  telegram:
    token: "8364473255:AAHKBLiP-ODq62r7Jv9Ex08FKNvEsiiMOjw"