#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER ${MIGRATION_USER} WITH PASSWORD '${MIGRATION_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${MIGRATION_USER};
  GRANT CREATE, USAGE ON SCHEMA public TO ${MIGRATION_USER};
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${MIGRATION_USER};
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${MIGRATION_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${MIGRATION_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${MIGRATION_USER};

  CREATE USER ${APP_USER} WITH PASSWORD '${APP_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${APP_USER};
  GRANT USAGE ON SCHEMA public TO ${APP_USER};
  GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${APP_USER};
  GRANT USAGE, SELECT ON ALL SEQUENCES TO ${APP_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${APP_USER};
EOSQL
